import sbtcrossproject.CrossPlugin.autoImport.{CrossType, crossProject}

ThisBuild / version      := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.8.2"

// SemanticDB is generated by Scala 3's compiler (no separate plugin needed)
// when `-Xsemanticdb` is on. Scalafix needs it for OrganizeImports +
// RemoveUnused. `-Wunused:all` is required by both rules so scalafix can
// trust the semantic info; existing `-Wconf:any:s` (per-project below)
// still silences the warning emission so build logs stay quiet — the
// semantic data is what scalafix actually reads, not the log output.
//
// Trade-off: ~5% compile time / disk overhead, only paid on recompile.
ThisBuild / scalacOptions ++= Seq("-Xsemanticdb", "-Wunused:all")
ThisBuild / semanticdbEnabled := true
ThisBuild / scalafixDependencies += "com.github.liancheng" %% "organize-imports" % "0.6.0"

// Tapir 1.11.x pulls in zio-json 0.7.x; we run 0.9.0. The breaking changes
// between those versions don't affect the APIs we rely on (Derive*,
// @jsonExplicitNull), so whitelist only that exact conflict. Other
// cross-version evictions will still surface as errors.
ThisBuild / libraryDependencySchemes ++= Seq(
  "dev.zio" %% "zio-json"        % VersionScheme.Always,
  "dev.zio" % "zio-json_sjs1_3"  % VersionScheme.Always,
  // zio-jdbc 0.1.2 still pins zio-schema 0.4.x; the transitive 1.x bumps
  // pulled in by zio-http and zio-redis ARE binary-compatible at the
  // surface zio-jdbc uses (Schema, BinaryCodec). Whitelist the eviction
  // rather than pin zio-jdbc to an older line.
  "dev.zio" %% "zio-schema"             % VersionScheme.Always,
  "dev.zio" %% "zio-schema-derivation"  % VersionScheme.Always,
  "dev.zio" %% "zio-schema-json"        % VersionScheme.Always,
  "dev.zio" %% "zio-schema-protobuf"    % VersionScheme.Always,
)

val zioVersion       = "2.1.26"
val zioHttpVersion   = "3.11.2"
val zioJsonVersion   = "0.9.0"
val zioKafkaVersion  = "2.10.0"
val laminarVersion   = "17.2.0"
val tapirVersion     = "1.11.36"
val slickVersion          = "3.6.1"
val postgresVersion       = "42.7.4"
val testcontainersVersion = "0.43.0"
val zioRedisVersion       = "1.1.3"
val zioSchemaVersion      = "1.7.2"
val mongoDriverVersion    = "5.5.1"
val zioRsInteropVersion   = "2.0.2"
val cassandraDriverVersion = "4.17.0"
val neo4jDriverVersion     = "5.28.5"
val clickhouseJdbcVersion  = "0.9.0"
val zioJdbcVersion         = "0.1.2"
// zio-spark's git `v0.13.0` tag (Spark 3.5.1) was never published to Maven
// Central — the latest *released* artifact is 0.12.0, which targets Spark 3.3.1
// (built on Scala 3.2.1, zio 2.0.5). We pin to what actually resolves and match
// its Spark line. Notably zio-spark has NO zio-json dependency, so there is no
// codec-version clash with the `events` module's zio-json 0.9.0.
val sparkVersion           = "3.3.1"
val zioSparkVersion        = "0.12.0"

// Spark 3.3 reflects into JDK internals that Java 17+ seals by default; these
// are the same `--add-opens` Spark's own launcher injects (its
// `JavaModuleOptions`). Required for the forked `sparkAnalytics/run` on a
// modern JDK. (Spark 3.3 officially supports Java 8/11/17; we run it on 21 —
// the closest JDK installed — which works for these local jobs with the opens.)
val sparkRunJavaOptions = Seq(
  // Force en-US locale so `f"%.1f"` prints "2.5" not the host-locale "2,5".
  "-Duser.language=en",
  "-Duser.country=US",
  // Hadoop's security layer (pulled by Spark) calls `Subject.getSubject`, which
  // Java 18+ refuses unless a security manager is explicitly allowed. Java 17
  // still permitted it; since we run on 21, opt in. (No SecurityManager is
  // actually installed — this just unblocks the legacy call.)
  "-Djava.security.manager=allow",
  "--add-opens=java.base/java.lang=ALL-UNNAMED",
  "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
  "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED",
  "--add-opens=java.base/java.io=ALL-UNNAMED",
  "--add-opens=java.base/java.net=ALL-UNNAMED",
  "--add-opens=java.base/java.nio=ALL-UNNAMED",
  "--add-opens=java.base/java.util=ALL-UNNAMED",
  "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED",
  "--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED",
  "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED",
  "--add-opens=java.base/sun.nio.cs=ALL-UNNAMED",
  "--add-opens=java.base/sun.security.action=ALL-UNNAMED",
  "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED",
  "--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED",
)
val gatlingVersion         = "3.13.5"
val zioMetricsConnectorsVersion = "2.5.6"
val zioOpenTelemetryVersion     = "3.0.0-RC24"
val openTelemetryVersion        = "1.43.0"
val zioProfilingVersion         = "0.3.3"

/** Group jars into separate Docker layers so a one-file source change only
  * invalidates the (small) project-jar layer, not the (large) 3rd-party-jar
  * layer. Reused by every service block.
  */
val pichessLayerGrouping: PartialFunction[(File, String), Int] = {
  case (_, path) =>
    val orgs = Set("com.", "org.", "io.", "dev.zio", "scala.")
    if (path.startsWith("/opt/docker/lib/") && orgs.exists(o => path.contains(s"/$o")))
      2 // layer 2: 3rd-party jars (rare changes)
    else if (path.startsWith("/opt/docker/lib/"))
      3 // layer 3: own project jars (every build)
    else
      4 // layer 4: bin/, conf/, etc.
}

// When PICHESS_PROFILE_BUILD=true at sbt invocation, the zio-profiling
// tagging compiler plugin is added everywhere. It rewrites every effect-
// returning def/val with `CostCenter.withChildCostCenter` so the
// sampling profiler can attribute time to source lines instead of the
// ZIO evaluation loop. The rewritten code adds synthetic statements
// that scoverage would count as uncovered, so coverage is also disabled
// in this mode — profile builds are *not* the same artifact as the
// CI/coverage-gated builds.
val profileBuildEnabled: Boolean =
  sys.env.get("PICHESS_PROFILE_BUILD").exists(_.equalsIgnoreCase("true"))

lazy val commonSettings = Seq(
  libraryDependencies ++= Seq(
    "dev.zio" %% "zio"          % zioVersion,
    "dev.zio" %% "zio-test"     % zioVersion % Test,
    "dev.zio" %% "zio-test-sbt" % zioVersion % Test,
  ) ++ (
    if (profileBuildEnabled)
      Seq(
        compilerPlugin(
          "dev.zio" %% "zio-profiling-tagging-plugin" % zioProfilingVersion
        ),
        // The plugin rewrites effect-returning defs/vals to call
        // `CostCenter.withChildCostCenter`, which lives in the
        // zio-profiling runtime jar. That jar is only declared in
        // `observabilityModule`, so non-observability modules (rules,
        // proto, persistence/api, …) fail to link the generated calls.
        // Bring the runtime to every plugin-tagged module.
        "dev.zio" %% "zio-profiling" % zioProfilingVersion
      )
    else Seq.empty
  ),
  testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
  // Coverage is opt-in via `sbt coverage test coverageReport`. Leaving it on
  // by default bakes scoverage's runtime agent into every compiled class,
  // which tries to write coverage data to the host path at startup and
  // breaks Docker containers with a FileNotFoundException. Do NOT set
  // `coverageEnabled := true` here for any reason — let scoverage's
  // default-off hold and let `sbt coverage <task>` flip it on per session.
  coverageMinimumStmtTotal := 100,
  coverageFailOnMinimum    := !profileBuildEnabled,
) ++ (
  // Profile builds add the tagging compiler plugin which emits synthetic
  // statements that scoverage would count as uncovered. Hard-force
  // coverage off in that mode so a `PICHESS_PROFILE_BUILD=true sbt
  // coverage …` still produces a usable artifact instead of a
  // scoverage-vs-plugin tug of war.
  if (profileBuildEnabled) Seq(coverageEnabled := false)
  else Seq.empty
)

// domain is shared with the Scala.js web-ui, so deps must resolve on both
// JVM and JS sides via %%%.
lazy val domain = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("domain"))
  .settings(
    name := "pichess-domain",
    libraryDependencies ++= Seq(
      "dev.zio" %%% "zio"          % zioVersion,
      "dev.zio" %%% "zio-test"     % zioVersion % Test,
      "dev.zio" %%% "zio-test-sbt" % zioVersion % Test,
    ),
    testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
  )
  .jvmSettings(
    coverageMinimumStmtTotal := 100,
    coverageFailOnMinimum    := true,
  )
  .jsSettings(
    // scoverage's runtime agent uses java.io.File / TrieMap and doesn't link
    // under Scala.js — leaving instrumentation on breaks `sbt coverage`.
    coverageEnabled := false,
  )

// Wire DTOs — single source of truth for the HTTP contract, shared by gateway
// (JVM encoder) and web-ui (JS decoder) via zio-json's cross-compiled codecs.
lazy val api = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("api"))
  // `domain` carries `GameState` etc. — needed by `WebBoardView.toDto`,
  // which moved into `api` so both the gateway (encoder side) and
  // game-service (now also producing the wire DTO directly) can use it.
  .dependsOn(domain)
  .settings(
    name := "pichess-api",
    libraryDependencies ++= Seq(
      "dev.zio"                     %%% "zio-json"            % zioJsonVersion,
      "com.softwaremill.sttp.tapir" %%% "tapir-core"          % tapirVersion,
      "com.softwaremill.sttp.tapir" %%% "tapir-json-zio"      % tapirVersion,
      // Binary `Pickler[BoardStateDto]` used to ship the DTO as the
      // `bytes` payload of `StateReply` over gRPC. boopickle was picked
      // after a JMH shoot-out (`BoardStateDtoBenchmark`) where
      // zio-schema-protobuf was 33× slower than the hand-tuned FEN
      // round-trip on our 64-square DTO. boopickle ties FEN (+5%) on a
      // binary wire format with single-Scala-source-of-truth, so we
      // keep the architectural pattern without the perf regression.
      "io.suzaku"                   %%% "boopickle"           % "1.5.0",
      "dev.zio"                     %%% "zio-test"            % zioVersion % Test,
      "dev.zio"                     %%% "zio-test-sbt"        % zioVersion % Test,
    ),
    testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
  )
  .jvmSettings(
    coverageMinimumStmtTotal := 100,
    coverageFailOnMinimum    := true,
  )
  .jsSettings(
    coverageEnabled := false,
  )

// Experiment infrastructure for the performance experiment. Tiny module
// — `Optimisation[T]` typeclass + a `select` method that picks between
// a `default` and a `baseline` ZLayer based on `PICHESS_OPT_<NAME>` env
// vars. Lets the perf suite A/B implementations without the service
// Main having to enumerate every variant. See docs/perf-experiments.md.
lazy val optimisation = project
  .in(file("optimisation"))
  .settings(commonSettings)
  .settings(name := "pichess-optimisation")

lazy val rules = project
  .in(file("rules"))
  .dependsOn(domain.jvm)
  .settings(commonSettings)
  .settings(name := "pichess-rules")

lazy val codec = project
  .in(file("codec"))
  .dependsOn(domain.jvm, rules)
  .settings(commonSettings)
  .settings(
    name := "pichess-codec",
    libraryDependencies ++= Seq(
      "dev.zio"                %% "zio-json"                 % zioJsonVersion,
      "org.scala-lang.modules" %% "scala-parser-combinators" % "2.4.0",
      "com.lihaoyi"            %% "fastparse"                % "3.1.1",
    ),
  )

// Chess-bot engine. Pure CPU search + evaluator on top of the bitboard
// rules layer — no DB / no network / no DTOs. Phase 1 is material-only
// eval + α-β with TT; Texel-tuned weights and opening-book hooks come
// in via later phases without touching this module's public surface.
//
// zio-json is pulled in solely for the WeightsCodec — loading the
// committed weights JSON resource at startup, the only piece of
// runtime serialisation the engine itself needs.
//
// codec is a main dependency (not Test-only) because the bot's
// portable opening book is committed as PGN and the engine has to
// parse it at startup via PgnParser. This makes bot-engine fully
// self-contained — clone + build + run, no DB.
lazy val botEngine = project
  .in(file("bot-engine"))
  .dependsOn(domain.jvm, rules, codec)
  .settings(commonSettings)
  .settings(
    name := "pichess-bot-engine",
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio-json" % zioJsonVersion,
    ),
  )

// Lichess Bot-API client + Bridge orchestrator. Parses the Lichess
// event stream, spawns a search fiber per accepted game, and POSTs
// chosen moves back. Reuses bot-engine for move selection and codec
// for FEN handling. sttp-zio + zio-streams for HTTP/SSE; zio-json for
// the Lichess JSON envelopes.
lazy val botLichess = project
  .in(file("bot-lichess"))
  .dependsOn(domain.jvm, rules, codec, botEngine)
  .settings(commonSettings)
  .settings(
    name := "pichess-bot-lichess",
    // LichessBotMain: runnable entry point (sbt runMain) — orchestration over
    // already-tested pieces (EngineBundle, Bridge, TimeManager, the tablebase
    // oracle); excluded from coverage like the other *Main entrypoints.
    coverageExcludedFiles := ".*LichessBotMain.*",
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.client3" %% "zio"      % "3.11.0",
      "dev.zio"                       %% "zio-json" % zioJsonVersion,
    ),
  )

// Tournament-server bot. Same shape as bot-lichess but speaks the NowChess
// Tournament API (maichess/tournament-server): register → join → stream the
// tournament → fork a budgeted search fiber per game → POST UCI moves. Reuses
// bot-engine for move selection (incl. the shared TimeManager) and codec for
// UCI/FEN. See docs/tournament-integration.md.
lazy val botTournament = project
  .in(file("bot-tournament"))
  .dependsOn(domain.jvm, rules, codec, botEngine)
  .settings(commonSettings)
  .settings(
    name := "pichess-bot-tournament",
    // TournamentBotMain: runnable entry point — orchestration over
    // already-tested pieces; excluded from coverage like the other *Main entrypoints.
    coverageExcludedFiles := ".*TournamentBotMain.*",
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.client3" %% "zio"      % "3.11.0",
      "dev.zio"                       %% "zio-json" % zioJsonVersion,
    ),
  )

// Training-data layer. DuckDB-backed: a single .duckdb file is the
// opening book at runtime AND the training corpus accumulator. JDBC
// only (zio-jdbc 0.1.2 in the build pins zio-schema 0.4.x — too old
// to be worth adopting here). Schema is created on open via
// CREATE TABLE IF NOT EXISTS so file lifecycles stay one-line simple.
//
// Depends on bot-engine so the BookRepo → OpeningBook adapter can
// expose itself as the engine's `OpeningBook` trait — upward
// dependency, but bot-data is conceptually a "data layer for the
// bot's engine" so this fits.
lazy val botData = project
  .in(file("bot-data"))
  .dependsOn(domain.jvm, codec, botEngine)
  .settings(commonSettings)
  .settings(
    name := "pichess-bot-data",
    libraryDependencies ++= Seq(
      "org.duckdb" % "duckdb_jdbc" % "1.1.3",
    ),
  )

// Offline training pipeline: PGN ingest, Texel tuner, self-play loop.
// Depends on codec (PgnParser) + bot-data (BookRepo/TrainingRepo); no
// network. Reads big PGN dumps and writes to the chess-bot.duckdb file.
//
// TrainMain is the runnable entry point; excluded from coverage
// because it's pure orchestration over already-tested pieces and
// requires a real corpus + filesystem to exercise meaningfully.
//
// `Compile / run / fork := true` and the explicit dep on bot-engine's
// `copyResources` prevent the v1.json classpath-staleness bug — sbt's
// in-process runner can otherwise launch with a stale classloader
// view of resources if the bot-engine `target/.../classes/weights/`
// hasn't been refreshed yet when runMain fires. Forking gets us a
// fresh JVM with the freshly-copied resources on its classpath.
lazy val botTrain = project
  .in(file("bot-train"))
  .dependsOn(domain.jvm, rules, codec, botData, botEngine)
  .settings(commonSettings)
  .settings(
    name := "pichess-bot-train",
    // TrainMain + TournamentMain + SfDistillMain + PolicyPriorMain:
    // orchestration entry points (sbt runMain), meaningful only with a
    // real PGN corpus / shared TSV. Their tested logic lives in pure
    // helpers (targetOutcome/sampleWeight/parseLine/accumulate/normalize).
    // StockfishSearch: external subprocess adapter, integration-tested in
    // StockfishSearchSpec when the binary is on PATH (skipped otherwise).
    coverageExcludedFiles := ".*(TrainMain|TournamentMain|StockfishSearch|SfDistillMain|PolicyPriorMain).*",
    Compile / run / fork := true,
    Compile / run := (Compile / run)
      .dependsOn(botEngine / Compile / copyResources)
      .evaluated,
  )

// Contract for the repository microservice — endpoint descriptions shared by
// its server (in `repository`) and its caller (`HttpGameRepository`).
lazy val repositoryApi = project
  .in(file("repository-api"))
  .settings(commonSettings)
  .settings(
    name := "pichess-repository-api",
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.tapir" %% "tapir-core"     % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-json-zio" % tapirVersion,
      "dev.zio"                     %% "zio-json"       % zioJsonVersion,
    ),
    // Two synthetic lambdas inside the `loadErrorOut` Tapir codec
    // definition can only be reached end-to-end through the server
    // interpreter — direct unit tests cover the codec helpers
    // (in `RepositoryCodecs.scala`, which stays in coverage) instead.
    coverageExcludedFiles := ".*RepositoryEndpoints.*",
  )

// Backend-agnostic persistence interface. Defines GameRepository and
// LobbyRepository traits + an in-memory impl that's the dev/test default.
// All real backends (Postgres, Mongo, Redis, Cassandra) live in their own
// downstream modules and depend on this one.
lazy val persistenceApi = project
  .in(file("persistence/api"))
  .dependsOn(domain.jvm)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-api",
  )

// Aggregator that knows how to wire every backend impl into a working
// `GameRepository` / `LobbyRepository` layer based on `BackendConfig`. The
// service Mains depend on just this one module instead of every backend
// module + the cache decorator individually.
lazy val persistenceRuntime = project
  .in(file("persistence/runtime"))
  .dependsOn(
    domain.jvm,
    persistenceApi,
    persistencePostgres,
    persistenceRedis,
    persistenceMongo,
    persistenceCassandra,
    persistenceCache
  )
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-runtime",
    libraryDependencies ++= Seq(
      // Tracing decorators (TracedGameRepository / TracedLobbyRepository)
      // wrap the selected backend with `tracing.span("db.<op>")` so DB-call
      // latency is visible per repo method in Jaeger.
      "dev.zio" %% "zio-opentelemetry" % zioOpenTelemetryVersion,
    ),
    // Layer-selection logic is exercised end-to-end in service-Main tests
    // and the contract module; not unit-coverable in isolation since each
    // branch needs the matching DB to be reachable.
    coverageEnabled := false,
  )

// Cache decorator: wraps any primary GameRepository/LobbyRepository with a
// Redis-backed front cache. Same pattern Phase 1's plan called out — flip
// PICHESS_CACHE=redis and the decorator slots in via ZLayer composition,
// no impl change needed at the call sites.
lazy val persistenceCache = project
  .in(file("persistence/cache"))
  .dependsOn(domain.jvm, persistenceApi, persistenceRedis)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-cache",
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio-redis"           % zioRedisVersion,
      "dev.zio" %% "zio-schema"          % zioSchemaVersion,
      "dev.zio" %% "zio-schema-protobuf" % zioSchemaVersion,
      "dev.zio" %% "zio-json"            % zioJsonVersion,
    ),
  )

// Cassandra backend: DataStax Java driver wrapped via ZIO.fromCompletionStage.
// (cassandra4io has no Scala 3 build, so we go straight to the Java API.)
lazy val persistenceCassandra = project
  .in(file("persistence/cassandra"))
  .dependsOn(domain.jvm, codec, persistenceApi)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-cassandra",
    libraryDependencies ++= Seq(
      "com.datastax.oss" % "java-driver-core" % cassandraDriverVersion,
    ),
    coverageEnabled := false,
  )

// MongoDB backend: official Java reactive-streams driver wrapped via
// zio-interop-reactivestreams. (mongo-scala-driver has no Scala 3 build, so
// we go straight to the Java API + a thin ZIO bridge.)
lazy val persistenceMongo = project
  .in(file("persistence/mongo"))
  .dependsOn(domain.jvm, codec, persistenceApi)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-mongo",
    libraryDependencies ++= Seq(
      "org.mongodb" %  "mongodb-driver-reactivestreams" % mongoDriverVersion,
      "dev.zio"     %% "zio-interop-reactivestreams"    % zioRsInteropVersion,
      "dev.zio"     %% "zio-json"                       % zioJsonVersion,
    ),
    coverageEnabled := false,
  )

// Redis backend: native zio-redis. Same impl is reused by persistence-cache
// as the cache backing store, so the trait we implement here is the
// boundary the decorator hits.
lazy val persistenceRedis = project
  .in(file("persistence/redis"))
  .dependsOn(domain.jvm, codec, persistenceApi)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-redis",
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio-redis"            % zioRedisVersion,
      "dev.zio" %% "zio-schema"           % zioSchemaVersion,
      "dev.zio" %% "zio-schema-protobuf"  % zioSchemaVersion,
      "dev.zio" %% "zio-json"             % zioJsonVersion,
    ),
    // Real-Redis tests live in persistence-contract via Testcontainers.
    coverageEnabled := false,
  )

// Shared zio-test contract suites that every backend impl must satisfy. Each
// concrete subclass provides a `ZLayer[Any, Throwable, GameRepository]` —
// usually built around a Testcontainers DB instance — and the contract suite
// runs the same set of save/load/delete invariants against it. A backend
// failing the contract is, by definition, not a drop-in replacement.
//
// Testcontainers needs Docker available at test time; CI gates on it.
lazy val persistenceContract = project
  .in(file("persistence/contract"))
  .dependsOn(
    domain.jvm,
    persistenceApi,
    persistencePostgres,
    persistenceRedis,
    persistenceMongo,
    persistenceCassandra
  )
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-contract",
    libraryDependencies ++= Seq(
      "com.dimafeng" %% "testcontainers-scala-postgresql" % testcontainersVersion % Test,
      "com.dimafeng" %% "testcontainers-scala-mongodb"    % testcontainersVersion % Test,
      "com.dimafeng" %% "testcontainers-scala-cassandra"  % testcontainersVersion % Test,
      "com.dimafeng" %% "testcontainers-scala-core"       % testcontainersVersion % Test,
    ),
    coverageEnabled := false,
  )

// PostgreSQL backend: Slick 3.6 + a tiny inline Future->ZIO bridge.
// (The community zio-slick-interop only publishes for Scala 2.13; the bridge
// it would have provided is a few lines of `ZIO.fromFuture` so we inline it
// here rather than block on a Scala 3 fork.)
lazy val persistencePostgres = project
  .in(file("persistence/postgres"))
  .dependsOn(domain.jvm, codec, persistenceApi, optimisation)
  .settings(commonSettings)
  .settings(
    name := "pichess-persistence-postgres",
    libraryDependencies ++= Seq(
      "com.typesafe.slick" %% "slick"          % slickVersion,
      "com.typesafe.slick" %% "slick-hikaricp" % slickVersion,
      "org.postgresql"     %  "postgresql"     % postgresVersion,
    ),
    // Real-DB integration tests live in persistence-contract and run via
    // Testcontainers; the impls in this module are exercised end-to-end there.
    // Coverage measured at the contract module, not here.
    coverageEnabled := false,
  )

// Kafka event ADT shared by gameService (producer) and repository (consumer).
// Single source of truth for what flows on the `chess.game-events` topic.
lazy val events = project
  .in(file("events"))
  .dependsOn(domain.jvm, codec)
  .settings(commonSettings)
  .settings(
    name := "pichess-events",
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio-json" % zioJsonVersion,
    ),
  )

// Generated zio-grpc stubs from proto/src/main/protobuf. Imported by gateway
// (client) and gameService (server). FEN strings cross the wire — Board/State
// stay out of the proto schema, that's the codec module's job.
lazy val proto = project
  .in(file("proto"))
  .settings(commonSettings)
  .settings(
    name := "pichess-proto",
    Compile / PB.targets := Seq(
      scalapb.gen(grpc = true)             -> (Compile / sourceManaged).value / "scalapb",
      scalapb.zio_grpc.ZioCodeGenerator    -> (Compile / sourceManaged).value / "scalapb",
    ),
    libraryDependencies ++= Seq(
      "io.grpc"                       %  "grpc-netty"            % "1.68.1",
      "com.thesamet.scalapb"          %% "scalapb-runtime-grpc"  % scalapb.compiler.Version.scalapbVersion,
      "com.thesamet.scalapb.zio-grpc" %% "zio-grpc-core"         % "0.6.3",
    ),
    // Generated code; coverage policy doesn't apply, and Scala 3 deprecation
    // warnings (private[this], `_` wildcards, `using` clauses) belong to
    // upstream scalapb's codegen — silenced here so they don't drown out
    // signal in our own modules.
    coverageEnabled := false,
    Compile / scalacOptions += "-Wconf:any:s",
  )

lazy val repository = project
  .in(file("repository"))
  .dependsOn(
    domain.jvm,
    repositoryApi,
    codec,
    events,
    persistenceApi,
    persistenceRuntime,
    observability
  )
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-repository",
    Compile / mainClass := Some("chess.repository.RepositoryMain"),
    libraryDependencies ++= Seq(
      "dev.zio"                       %% "zio-http"              % zioHttpVersion,
      "dev.zio"                       %% "zio-kafka"             % zioKafkaVersion,
      "dev.zio"                       %% "zio-kafka-testkit"     % zioKafkaVersion % Test,
      "com.softwaremill.sttp.tapir"   %% "tapir-zio-http-server" % tapirVersion,
      "com.softwaremill.sttp.tapir"   %% "tapir-sttp-client"     % tapirVersion,
      "com.softwaremill.sttp.client3" %% "zio"                   % "3.11.0",
    ),
    Docker / packageName := "pichess-repository",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerExposedPorts   := Seq(8091),
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    // HTTP wiring (Main, server) is exercised by docker-compose smoke
    // tests, not unit coverage — matches the LobbyServer/AnalyticsServer
    // exclusion pattern. Kafka-backed code needs a live broker; same
    // story. Repository's pure business logic lives in the persistence
    // backends, which are contract-tested via real DB testcontainers.
    coverageExcludedFiles :=
      ".*Kafka.*;.*RepositoryMain.*;.*RepositoryServer.*",
  )

lazy val gameService = project
  .in(file("game-service"))
  .dependsOn(
    domain.jvm,
    rules,
    codec,
    events,
    proto,
    api.jvm,
    persistenceApi,
    persistenceRuntime,
    observability,
    // vs-bot integration: game-service composes engine-search with the
    // chess-game lifecycle. bot-engine is pure CPU code so this adds
    // no transitive infra burden.
    botEngine,
  )
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-game-service",
    Compile / mainClass := Some("chess.gameservice.GameServiceMain"),
    libraryDependencies ++= Seq(
      "dev.zio"          %% "zio-kafka"         % zioKafkaVersion,
      "dev.zio"          %% "zio-kafka-testkit" % zioKafkaVersion % Test,
      "io.grpc"          %  "grpc-services"     % "1.68.1",
    ),
    // grpc-netty 1.68 ships netty-codec 4.1.x; zio-http 3.10 ships
    // netty-codec-http 4.2.x. The 4.2.x http codec calls
    // `DefaultHeaders.containsAny(_, _, BiPredicate)` which doesn't
    // exist on 4.1.x — manifests at runtime as a NoSuchMethodError on
    // every metrics scrape. Pin both codec jars to 4.2.x so the http
    // codec finds the method it expects.
    dependencyOverrides ++= Seq(
      "io.netty" % "netty-codec"       % "4.2.10.Final",
      "io.netty" % "netty-codec-http2" % "4.2.10.Final",
    ),
    Docker / packageName := "pichess-game-service",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerExposedPorts   := Seq(9000),
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    // Kafka- and gRPC-Server-Main-backed code needs a live broker / port to
    // exercise; covered by docker-compose smoke tests, not unit coverage.
    coverageExcludedFiles :=
      ".*Kafka.*;.*GameServiceMain.*;.*GrpcServer.*",
  )

// Supplementary projection: builds a graph of opening positions by
// consuming chess.game-events and walking each MoveMade into Neo4j as a
// (Position{fen})-[:MOVE{san,count}]->(Position{fen}) edge. Read-only from
// the perspective of game state — never serves the primary GameRepository.
lazy val openingService = project
  .in(file("opening-service"))
  .dependsOn(domain.jvm, codec, events, observability)
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-opening-service",
    Compile / mainClass := Some("chess.opening.OpeningMain"),
    libraryDependencies ++= Seq(
      "dev.zio"          %% "zio-kafka"        % zioKafkaVersion,
      "org.neo4j.driver" %  "neo4j-java-driver" % neo4jDriverVersion,
    ),
    Docker / packageName := "pichess-opening-service",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    coverageExcludedFiles :=
      ".*OpeningMain.*;.*Kafka.*;.*Neo4j.*",
  )

// Supplementary projection: ClickHouse OLAP store fed by chess.game-events.
// Holds an append-only `move_events` table plus aggregate views; serves
// canonical aggregate queries over a small REST surface so the future
// admin panel can call it without speaking JDBC.
lazy val analyticsService = project
  .in(file("analytics-service"))
  .dependsOn(domain.jvm, codec, events, observability)
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-analytics-service",
    Compile / mainClass := Some("chess.analytics.AnalyticsMain"),
    libraryDependencies ++= Seq(
      "dev.zio"                     %% "zio-kafka"             % zioKafkaVersion,
      "dev.zio"                     %% "zio-jdbc"              % zioJdbcVersion,
      "dev.zio"                     %% "zio-http"              % zioHttpVersion,
      "dev.zio"                     %% "zio-json"              % zioJsonVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-core"            % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-json-zio"        % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-zio-http-server" % tapirVersion,
      "com.clickhouse"              %  "clickhouse-jdbc"       % clickhouseJdbcVersion,
    ),
    Docker / packageName := "pichess-analytics-service",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerExposedPorts   := Seq(8093),
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    // DB-touching files (projection, service, schema, JSON codecs, HTTP
    // wiring) are exercised end-to-end against a live ClickHouse, not as
    // unit tests. Pure logic in AnalyticsEventMapping IS unit-tested.
    coverageExcludedFiles :=
      ".*AnalyticsMain.*;.*Kafka.*;.*ClickHouse.*;.*AnalyticsServer.*;" +
        ".*AnalyticsEndpoints.*;.*AnalyticsProjection.*;.*LiveAnalyticsService.*;" +
        ".*AnalyticsSchema.*",
  )

// Spark analytics — Lambda-architecture read-side projection over the same
// `chess.game-events` log. Batch job reads an archived event dump from file;
// the streaming job connects Spark Structured Streaming to Kafka. Both feed the
// same `Aggregations` transforms.
//
// Scala-version note: Spark has no Scala 3 build, so spark-core/spark-sql are
// pulled as their Scala 2.13 artifacts via `.cross(CrossVersion.for3Use2_13)`,
// kept `% Provided` (the Spark runtime supplies them on a real cluster).
//
// This module pins **Scala 3.3 (LTS)**, NOT the repo's 3.8.2, for one concrete
// reason: Spark's runtime encoders use `scala-reflect:2.13.8`, whose
// `JavaUniverse` must reflect over a *genuine* 2.13 standard library. Scala
// 3.7+ publishes its own standalone `scala-library:3.x` (which carries Scala-3
// stdlib classes like `scala.deriving.Mirror`), and scala-reflect chokes on it
// ("class Array does not have a member apply" at init). The 3.3 LTS line still
// depends on a genuine `scala-library:2.13.16`, giving Spark the coherent 2.13
// toolchain it needs — and it's the exact line zio-spark 0.12.0 was built on.
//
// Consequence: a 3.3 compiler can't read the 3.8.2 TASTy of `events`/`codec`,
// so this module does NOT `dependsOn` them. The schema boundary is instead a
// standalone re-declaration (`schema/RawGameEvent`) — a minimal zio-json mirror
// of the canonical `chess.events.GameDomainEvent` JSON. Spark drags in a large,
// jackson/netty-heavy transitive closure, so the module is kept OUT of the root
// aggregate — build it with `sparkAnalytics/compile`.
lazy val sparkAnalytics = project
  .in(file("spark-analytics"))
  .settings(commonSettings)
  .settings(
    name         := "pichess-spark-analytics",
    scalaVersion := "3.3.6",
    libraryDependencies ++= Seq(
      "dev.zio"           %% "zio-json"             % zioJsonVersion,
      "io.univalence"     %% "zio-spark"            % zioSparkVersion,
      ("org.apache.spark" %% "spark-core"           % sparkVersion % Provided)
        .cross(CrossVersion.for3Use2_13),
      ("org.apache.spark" %% "spark-sql"            % sparkVersion % Provided)
        .cross(CrossVersion.for3Use2_13),
      ("org.apache.spark" %% "spark-sql-kafka-0-10" % sparkVersion)
        .cross(CrossVersion.for3Use2_13),
    ),
    // Spark ships `scala-reflect:2.13.8`; match it to the genuine 2.13.16 stdlib
    // that scala3-library 3.3.6 pulls, so the reflection toolchain is coherent
    // (an older reflect over a newer 2.13 library can still misfire).
    dependencyOverrides += "org.scala-lang" % "scala-reflect" % "2.13.16",
    // Spark assemblies bundle their own Scala 2.13 stdlib + jackson; this
    // module is an isolated island talking only over Kafka/files, so it isn't
    // unit-covered here (jobs are exercised against a local SparkSession).
    coverageEnabled := false,
    // `run`/`runMain` against a local SparkSession: fork a JVM with the Spark
    // module-opens, and put `% Provided` Spark jars on the run classpath (they
    // are excluded from the default `Runtime` classpath but supplied by the
    // cluster in production — locally we are the cluster). Uses `fullClasspath`
    // (= Compile classpath, which includes Provided).
    fork := true,
    // Spark 3.3 requires Java 17 (Java 21+ removed DirectByteBuffer(long,int)
    // that Spark's Platform reflects into). The JVM running sbt may be newer,
    // so pin the forked run's JDK via PICHESS_SPARK_JAVA_HOME when set.
    Compile / run / javaHome :=
      sys.env.get("PICHESS_SPARK_JAVA_HOME").map(file),
    javaOptions ++= sparkRunJavaOptions,
    // Forked runs default their working dir to the module dir; pin it to the
    // repo root so repo-root-relative data paths (spark-analytics/data/...)
    // resolve the same way whether invoked from root or the module.
    Compile / run / baseDirectory := (LocalRootProject / baseDirectory).value,
    Compile / run := Defaults
      .runTask(
        Compile / fullClasspath,
        Compile / run / mainClass,
        Compile / run / runner
      )
      .evaluated,
    Compile / runMain := Defaults
      .runMainTask(Compile / fullClasspath, Compile / run / runner)
      .evaluated,
  )

// New microservice for lobby management. REST-only on :8092 — no gRPC, no
// Kafka in Phase 1 (lobby events come later, see plan §"Future scope"). Uses
// `LobbyRepository` from persistence-api so it inherits the same backend
// swap as game state.
lazy val lobbyService = project
  .in(file("lobby-service"))
  .dependsOn(
    domain.jvm,
    api.jvm,
    persistenceApi,
    persistenceRuntime,
    observability
  )
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-lobby-service",
    Compile / mainClass := Some("chess.lobby.LobbyMain"),
    libraryDependencies ++= Seq(
      "dev.zio"                     %% "zio-http"              % zioHttpVersion,
      "dev.zio"                     %% "zio-json"              % zioJsonVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-core"            % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-json-zio"        % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-zio-http-server" % tapirVersion,
      // Outbound HTTP to the gateway (internal /players hand-off).
      "com.softwaremill.sttp.tapir"   %% "tapir-sttp-client" % tapirVersion,
      "com.softwaremill.sttp.client3" %% "zio"               % "3.11.0",
    ),
    Docker / packageName := "pichess-lobby-service",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerExposedPorts   := Seq(8092),
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    // HTTP wiring (Main, server, endpoint defs) is exercised by docker-compose
    // smoke tests, not unit coverage. LobbyService logic is covered here.
    // LobbyJson is pure codec/value code — kept in coverage.
    coverageExcludedFiles :=
      ".*LobbyMain.*;.*LobbyServer.*;.*LobbyEndpoints.*",
  )

lazy val gateway = project
  .in(file("gateway"))
  .dependsOn(gameService, codec, api.jvm, proto, observability)
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-gateway",
    Compile / mainClass := Some("chess.gateway.GatewayMain"),
    libraryDependencies ++= Seq(
      "dev.zio"                     %% "zio-http"                 % zioHttpVersion,
      "dev.zio"                     %% "zio-json"                 % zioJsonVersion,
      // Live-analytics loop-back: consume the `chess.analytics` topic that the
      // Spark speed layer publishes, relay it to the web-ui over SSE.
      "dev.zio"                     %% "zio-kafka"                % zioKafkaVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-zio-http-server"    % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-swagger-ui-bundle"  % tapirVersion,
      "io.grpc"                     %  "grpc-inprocess"           % "1.68.1" % Test,
    ),
    Docker / packageName := "pichess-gateway",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerExposedPorts   := Seq(8090),
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    // GatewayMain: runnable entry point. LichessSpectate: external-I/O bridge
    // (Lichess HTTP API + game-service gRPC + a follower fiber) — integration
    // glue, not meaningfully unit-testable without a live Lichess + game
    // service, like the other external adapters (StockfishSearch).
    coverageExcludedFiles := ".*(GatewayMain|LichessSpectate|AnalyticsRelay|AnalyticsRoutes).*",
    // Copy the Scala.js output of web-ui into gateway's managed resources at
    // web/main.js so WebController can serve it from the classpath.
    Compile / resourceGenerators += Def.task {
      val report = (webUi / Compile / fastLinkJS).value
      val linkerDir =
        (webUi / Compile / fastLinkJS / scalaJSLinkerOutputDirectory).value
      val targetDir = (Compile / resourceManaged).value / "web"
      IO.createDirectory(targetDir)
      report.data.publicModules.toSeq.flatMap { m =>
        val src = linkerDir / m.jsFileName
        val dst = targetDir / m.jsFileName
        IO.copyFile(src, dst)
        val maybeMap = linkerDir / (m.jsFileName + ".map")
        val mapOut =
          if (maybeMap.exists()) {
            val mapDst = targetDir / (m.jsFileName + ".map")
            IO.copyFile(maybeMap, mapDst)
            Some(mapDst)
          } else None
        Seq(dst) ++ mapOut
      }
    }.taskValue,
  )

// Stress / load tests via Gatling. Hits the gateway's HTTP surface; doesn't
// know which backend is wired in — that's the point. Run the same scenario
// with PICHESS_BACKEND=postgres / mongo / redis / cassandra to produce
// comparative throughput numbers under `gatling/target/gatling/`.
//
// Run with:  sbt 'gatling/Gatling/test'      (all simulations)
//            sbt 'gatling/Gatling/testOnly chess.gatling.GameSimulation'
lazy val gatling = project
  .in(file("gatling"))
  .enablePlugins(GatlingPlugin)
  .settings(
    name := "pichess-gatling",
    scalaVersion := "3.8.2",
    libraryDependencies ++= Seq(
      "io.gatling.highcharts" % "gatling-charts-highcharts" % gatlingVersion % Test,
      "io.gatling"            % "gatling-test-framework"    % gatlingVersion % Test,
    ),
    coverageEnabled := false,
    // Gatling 3.x uses MethodHandles.privateLookupIn against java.lang
    // internals (StringInternals) which JDK 17+ closes off by default.
    // Open just what Gatling actually touches at runtime.
    Test / fork := true,
    Test / javaOptions ++= Seq(
      "--add-opens=java.base/java.lang=ALL-UNNAMED",
      "--add-opens=java.base/java.util=ALL-UNNAMED",
    ),
  )

// Cross-cutting observability layer shared by every service: Prometheus
// metrics exposition, OpenTelemetry tracing, and zio-profiling sampling.
// Each service Main pulls these in and wires them next to its main HTTP
// or gRPC listener — see `chess.obs.MetricsHttpServer` for the
// per-service `/metrics` endpoint wiring.
lazy val observability = project
  .in(file("observability"))
  .dependsOn(domain.jvm)
  .settings(commonSettings)
  .settings(
    name := "pichess-observability",
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio-http"                            % zioHttpVersion,
      "dev.zio" %% "zio-metrics-connectors"              % zioMetricsConnectorsVersion,
      "dev.zio" %% "zio-metrics-connectors-prometheus"   % zioMetricsConnectorsVersion,
      "dev.zio" %% "zio-opentelemetry"                   % zioOpenTelemetryVersion,
      "io.opentelemetry" %  "opentelemetry-sdk"          % openTelemetryVersion,
      "io.opentelemetry" %  "opentelemetry-exporter-otlp" % openTelemetryVersion,
      "io.opentelemetry" %  "opentelemetry-sdk-extension-autoconfigure" % openTelemetryVersion,
      "dev.zio" %% "zio-profiling"                       % zioProfilingVersion,
    ),
    // Coverage is exercised end-to-end via the perf harness once a
    // service Main mounts these layers; the layer-construction code
    // itself isn't unit-testable in isolation.
    coverageEnabled := false,
  )

// Microbenchmarks for chess-engine internals via JMH. Targets the pure-
// functional hot paths the gateway-level Gatling suite can't isolate:
// move generation, legal-move filtering, FEN/SAN parsing, Zobrist
// hashing. Output is JSON so the perf-run harness can fold it into a
// cross-backend comparison report.
//
// Run with:  sbt 'bench/Jmh/run -i 5 -wi 5 -f1 chess.bench.FenParserBenchmark'
lazy val bench = project
  .in(file("bench"))
  .dependsOn(domain.jvm, rules, codec, api.jvm, botEngine, botTrain)
  .enablePlugins(JmhPlugin)
  .settings(
    name         := "pichess-bench",
    scalaVersion := "3.8.2",
    libraryDependencies ++= Seq(
      "dev.zio"   %% "zio"       % zioVersion,
      // Bench-only — compared against zio-schema-protobuf and zio-json
      // to understand whether the BoardStateDto wire-format cost is a
      // codec choice or fundamental to the round-trip.
      "io.suzaku" %% "boopickle" % "1.5.0",
    ),
    coverageEnabled := false,
  )

// TUI is currently a parser-only library. Runtime (stdin loop + REST client
// Container-friendly text UI. Reads commands from stdin, calls the gateway
// over HTTP using the typed `chess.api.Endpoints` (same Tapir contract the
// web-ui uses), and renders results back to stdout. Runs in its own
// container so a TUI crash can't kill the gateway and so spinning up
// multiple instances (e.g. bots-vs-bots) doesn't require gateway changes.
lazy val tui = project
  .in(file("tui"))
  .dependsOn(domain.jvm, codec, api.jvm)
  .enablePlugins(JavaAppPackaging, DockerPlugin)
  .settings(commonSettings)
  .settings(
    name := "pichess-tui",
    Compile / mainClass := Some("chess.tui.TuiMain"),
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.tapir"   %% "tapir-sttp-client" % tapirVersion,
      "com.softwaremill.sttp.client3" %% "zio"               % "3.11.0",
      // Lobby JSON wire types are decoded in TuiClient — gateway proxies
      // /lobbies/* to the lobby-service so we don't need a Tapir contract,
      // just a small zio-json codec mirror of the fields we read.
      "dev.zio"                       %% "zio-json"          % zioJsonVersion,
    ),
    Docker / packageName := "pichess-tui",
    Docker / version     := "latest",
    dockerBaseImage      := "eclipse-temurin:23-jre",
    dockerUpdateLatest   := true,
    Docker / dockerGroupLayers := pichessLayerGrouping,
    coverageExcludedFiles :=
      ".*TuiMain.*;.*TuiClient.*;.*TuiEventStream.*",
  )

lazy val webUi = project
  .in(file("web-ui"))
  .enablePlugins(ScalaJSPlugin)
  .dependsOn(domain.js, api.js)
  .settings(
    name                            := "pichess-web-ui",
    scalaJSUseMainModuleInitializer := true,
    libraryDependencies ++= Seq(
      "com.raquo"                   %%% "laminar"           % laminarVersion,
      "com.softwaremill.sttp.tapir" %%% "tapir-sttp-client" % tapirVersion,
      "dev.zio"                     %%% "zio-test"          % zioVersion % Test,
      "dev.zio"                     %%% "zio-test-sbt"      % zioVersion % Test,
    ),
    testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
    // Scoverage doesn't instrument Scala.js output, so coverage stays off here
    // even when someone runs `sbt coverage test coverageReport` globally.
    coverageEnabled := false,
  )

lazy val root = project
  .in(file("."))
  .aggregate(
    domain.jvm,
    domain.js,
    api.jvm,
    api.js,
    rules,
    codec,
    repositoryApi,
    persistenceApi,
    persistencePostgres,
    persistenceRedis,
    persistenceMongo,
    persistenceCassandra,
    persistenceCache,
    persistenceRuntime,
    persistenceContract,
    events,
    proto,
    repository,
    gameService,
    lobbyService,
    openingService,
    analyticsService,
    gateway,
    tui,
    webUi,
    gatling,
    bench,
    observability,
  )
  .settings(
    name := "pichess",
    // `sbt run` at the root has no single Main since the app monolith was
    // split into separate gateway / gameService / repository services. Use
    // `sbt <svc>/run` for individual services or `docker compose up` for the
    // integrated stack.
  )

// Build all seven service images into the local Docker daemon. Run this
// once before `docker compose up` (and after every service-side change).
// Listed in dependency order — domain/persistence libs are pulled in
// transitively — so a single `sbt dockerBuildAll` is enough.
addCommandAlias(
  "dockerBuildAll",
  Seq(
    "gameService/Docker/publishLocal",
    "repository/Docker/publishLocal",
    "lobbyService/Docker/publishLocal",
    "openingService/Docker/publishLocal",
    "analyticsService/Docker/publishLocal",
    "gateway/Docker/publishLocal",
    "tui/Docker/publishLocal"
  ).mkString(";", ";", "")
)
