addSbtPlugin("org.scoverage"      % "sbt-scoverage"             % "2.2.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.20.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"       % "1.10.4")
