package chess.analytics

import zio.*
import zio.jdbc.*

import java.sql.{Connection, PreparedStatement, ResultSet, Timestamp}

/** ClickHouse-compatible JDBC helpers.
  *
  * zio-jdbc 0.1.2's `SqlFragment.execute` / `.insert` / `.query` always go
  * through `Connection.prepareStatement(sql, autoGeneratedKeys: Int)`, but
  * the ClickHouse JDBC driver throws `SQLFeatureNotSupportedException` for
  * that overload. These helpers drop to the underlying `Connection` and
  * use the no-arg `prepareStatement(sql)` instead.
  *
  * Parameters are positional `?` placeholders, bound in order via
  * `setObject`. The driver's type coercion handles strings, numerics,
  * timestamps. Add a typed binder here if a future call site needs
  * something exotic (arrays, custom enums).
  */
object ClickHouseJdbc:

  /** Execute a DDL/DML statement with no result set (CREATE TABLE,
    * INSERT, ALTER, DELETE…). */
  def execute(sql: String, params: Any*): RIO[ZConnectionPool, Unit] =
    withConn { conn =>
      withStatement(conn, sql, params) { ps =>
        ps.executeUpdate()
        ()
      }
    }

  /** Run a `SELECT` and decode each row through the supplied function. */
  def query[A](
      sql: String,
      params: Any*
  )(decode: ResultSet => A): RIO[ZConnectionPool, List[A]] =
    withConn { conn =>
      withStatement(conn, sql, params) { ps =>
        val rs = ps.executeQuery()
        try
          val builder = List.newBuilder[A]
          while rs.next() do builder += decode(rs)
          builder.result()
        finally rs.close()
      }
    }

  /** Convenience: run a `SELECT` that returns at most one row. */
  def queryOne[A](
      sql: String,
      params: Any*
  )(decode: ResultSet => A): RIO[ZConnectionPool, Option[A]] =
    query(sql, params*)(decode).map(_.headOption)

  // --- internals -----------------------------------------------------------

  private def withConn[A](
      f: Connection => A
  ): RIO[ZConnectionPool, A] =
    transaction {
      ZIO.serviceWithZIO[ZConnection](_.access(f))
    }

  private def withStatement[A](
      conn: Connection,
      sql: String,
      params: Seq[Any]
  )(use: PreparedStatement => A): A =
    val ps = conn.prepareStatement(sql)
    try
      bindParams(ps, params)
      use(ps)
    finally ps.close()

  private def bindParams(ps: PreparedStatement, params: Seq[Any]): Unit =
    var idx = 1
    params.foreach { p =>
      p match
        case null               => ps.setObject(idx, null)
        case t: Timestamp       => ps.setTimestamp(idx, t)
        case s: String          => ps.setString(idx, s)
        case b: Boolean         => ps.setBoolean(idx, b)
        case i: Int             => ps.setInt(idx, i)
        case l: Long            => ps.setLong(idx, l)
        case d: Double          => ps.setDouble(idx, d)
        case other              => ps.setObject(idx, other)
      idx += 1
    }
