#!/usr/bin/env bash
#
# perf-report.sh — generates performance-test-results.md from a
# perf-reports/<TS>/ run directory.
#
# Picks up whatever is in the run dir:
#   matrix/<bk>+<cache>/<workload>/        — DB matrix (from `make db-matrix`)
#   <backend>/                             — single Gatling run (from `make perf`)
#   k6/<surface>/                          — k6 surfaces (from `make k6`)
#   bench.json                             — JMH JSON (from `make perf-all`)
#   bench-<ts>.json (at perf-reports root) — standalone `make bench`
#
# Output: <run-dir>/performance-test-results.md.
#
# Usage:
#   scripts/perf-report.sh                              # most recent run dir
#   scripts/perf-report.sh perf-reports/20260603T010203Z
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

RUN_DIR="${1:-}"
if [[ -z "$RUN_DIR" ]]; then
  RUN_DIR="$(ls -dt perf-reports/2*/ 2>/dev/null | head -1)"
  if [[ -z "$RUN_DIR" ]]; then
    echo "no run dirs under perf-reports/ — pass one explicitly or do a run first" >&2
    exit 1
  fi
  RUN_DIR="${RUN_DIR%/}"
fi

if [[ ! -d "$RUN_DIR" ]]; then
  echo "not a directory: $RUN_DIR" >&2
  exit 1
fi

GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
HOST="$(uname -srm 2>/dev/null || echo unknown)"
DOCKER_VER="$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo unknown)"

python3 - "$RUN_DIR" "$GIT_SHA" "$GIT_BRANCH" "$HOST" "$DOCKER_VER" <<'PY'
import json, os, re, sys

run_dir, git_sha, git_branch, host, docker_ver = sys.argv[1:6]
ts = os.path.basename(run_dir.rstrip("/"))
out_path = os.path.join(run_dir, "performance-test-results.md")

lines = []
def emit(s=""): lines.append(s)

# ────────────────────────── header ──────────────────────────────────────
emit(f"# Performance test results — {ts}")
emit("")
emit("> Generated by `make perf-report`. Sources for every number cited "
     f"below live under `{run_dir}/`.")
emit("")
emit("## Run metadata")
emit("")
emit(f"- Timestamp (UTC): `{ts}`")
emit(f"- Git: `{git_sha}` on `{git_branch}`")
emit(f"- Host: `{host}`")
emit(f"- Docker server: `{docker_ver}`")

# ── selectors (PICHESS_OPT_*) — captured at run start by db-matrix /
# perf-run / perf-all. If selectors.env is missing (older run dir, or
# the user ran the report standalone), fall back to the current
# environment as a best-effort.
selectors = {}
sel_path = os.path.join(run_dir, "selectors.env")
if os.path.isfile(sel_path):
    with open(sel_path) as f:
        for line in f:
            line = line.strip()
            if "=" in line and line.startswith("PICHESS_OPT_"):
                k, v = line.split("=", 1)
                selectors[k] = v
else:
    for k, v in os.environ.items():
        if k.startswith("PICHESS_OPT_"):
            selectors[k] = v

if selectors:
    emit(f"- Optimisation selectors at run time:")
    for k in sorted(selectors):
        emit(f"  - `{k}={selectors[k]}`")
else:
    emit(f"- Optimisation selectors at run time: all defaults")
emit("")

# ─────────────────────── helpers ────────────────────────────────────────

def read_kv(path):
    """Parse a key=value summary.txt file."""
    out = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if "=" in line:
                    k, v = line.split("=", 1)
                    out[k] = v
    except FileNotFoundError:
        pass
    return out


def parse_prom_snapshot(path):
    """Parse a Prometheus instant-vector snapshot. Returns
    {service: {metric_name: [(labels_tuple, float_value), ...]}}.
    The `service` key is derived from the Prometheus `instance` label
    (e.g. `gateway:9101` → `gateway`) — Prometheus scrapes all six
    services under a single `job=pichess`, so the per-service split has
    to come from the host portion of the instance.
    """
    by_svc = {}
    try:
        d = json.load(open(path))
    except (FileNotFoundError, json.JSONDecodeError):
        return by_svc
    results = d.get("data", {}).get("result", [])
    for r in results:
        m = r.get("metric", {})
        name = m.get("__name__")
        instance = m.get("instance", "?")
        # instance format: "<service-hostname>:<port>".
        svc = instance.split(":", 1)[0] if ":" in instance else instance
        try:
            v = float(r.get("value", [0, "0"])[1])
        except (ValueError, TypeError):
            continue
        labels = tuple(sorted((k, v) for k, v in m.items() if k not in ("__name__",)))
        by_svc.setdefault(svc, {}).setdefault(name, []).append((labels, v))
    return by_svc


def heap_used_total(by_svc, svc):
    """Sum jvm_memory_used_bytes across heap pools for one service."""
    metrics = by_svc.get(svc, {})
    series = metrics.get("jvm_memory_used_bytes", [])
    if not series:
        return None
    total = 0.0
    for labels, v in series:
        d = dict(labels)
        # area="heap" distinguishes heap vs nonheap
        if d.get("area", "heap") == "heap":
            total += v
    return total if total > 0 else None


def first_value(by_svc, svc, metric_name):
    series = by_svc.get(svc, {}).get(metric_name, [])
    if not series:
        return None
    # Sum across labels (e.g. per-pool, per-GC, …)
    return sum(v for _, v in series)


def delta(baseline, final, svc, metric_name):
    a = first_value(baseline, svc, metric_name)
    b = first_value(final,    svc, metric_name)
    if a is None or b is None:
        return None
    return b - a


def fmt_bytes(n):
    if n is None: return "n/a"
    units = [("GB", 1024**3), ("MB", 1024**2), ("KB", 1024), ("B", 1)]
    for unit, scale in units:
        if abs(n) >= scale:
            return f"{n / scale:.1f} {unit}"
    return f"{n:.0f} B"


def fmt_sec(n):
    if n is None: return "n/a"
    if n < 0.001: return f"{n*1_000_000:.1f} µs"
    if n < 1:     return f"{n*1000:.1f} ms"
    return f"{n:.2f} s"


def fmt_count(n):
    if n is None: return "n/a"
    return f"{n:,.0f}"


# ──────────────── matrix section (DB experiment) ────────────────────────

matrix_dir = os.path.join(run_dir, "matrix")
matrix_rows = []
if os.path.isdir(matrix_dir):
    for cfg in sorted(os.listdir(matrix_dir)):
        cfg_path = os.path.join(matrix_dir, cfg)
        if not os.path.isdir(cfg_path):
            continue
        for wl in sorted(os.listdir(cfg_path)):
            wl_path = os.path.join(cfg_path, wl)
            if not os.path.isdir(wl_path):
                continue
            kv = read_kv(os.path.join(wl_path, "summary.txt"))
            baseline = parse_prom_snapshot(
                os.path.join(wl_path, "prometheus-baseline.json"))
            final = parse_prom_snapshot(
                os.path.join(wl_path, "prometheus-final.json"))
            matrix_rows.append({
                "config":  cfg,
                "backend": kv.get("backend", "?"),
                "cache":   kv.get("cache", "?"),
                "workload": kv.get("mode", wl),
                "requests_ok": kv.get("requests_ok", "?"),
                "requests_ko": kv.get("requests_ko", "?"),
                "mean_rps":    kv.get("mean_rps", "?"),
                "p50_ms":      kv.get("p50_ms", "?"),
                "p95_ms":      kv.get("p95_ms", "?"),
                "p99_ms":      kv.get("p99_ms", "?"),
                "baseline": baseline,
                "final":    final,
            })

if matrix_rows:
    emit("## DB matrix")
    emit("")
    emit("Per workload, configs are ranked by p95 latency (lower is better). "
         "The matrix is generated by `make db-matrix` and reads "
         f"`{matrix_dir}/<backend>+<cache>/<workload>/summary.txt` for each cell.")
    emit("")

    def safe_float(s, default=float("inf")):
        try: return float(s)
        except: return default

    workloads = sorted({r["workload"] for r in matrix_rows})
    for wl in workloads:
        emit(f"### Workload: {wl}")
        emit("")
        emit("| Rank | Backend | Cache | Req OK | Req KO | Mean RPS | p50 ms | p95 ms | p99 ms |")
        emit("|---:|---|---|---:|---:|---:|---:|---:|---:|")
        wl_rows = [r for r in matrix_rows if r["workload"] == wl]
        wl_rows.sort(key=lambda r: safe_float(r["p95_ms"]))
        for i, r in enumerate(wl_rows, start=1):
            emit(
                f"| {i} | {r['backend']} | {r['cache']} | "
                f"{r['requests_ok']} | {r['requests_ko']} | "
                f"{r['mean_rps']} | {r['p50_ms']} | "
                f"{r['p95_ms']} | {r['p99_ms']} |"
            )
        emit("")

    # ── Resource profile from Prometheus ────────────────────────────────
    emit("## Resource profile (from Prometheus)")
    emit("")
    emit("Per backend×cache config, the resources each service used during the "
         "run. Heap is the post-run instant value (a proxy for steady-state "
         "peak); GC time and pause count are the delta between baseline and "
         "final snapshots; CPU is process-CPU seconds consumed during the run.")
    emit("")
    emit("Services covered: `gateway`, `game-service`, `repository`, "
         "`lobby-service`. Opening / analytics consumers are present only when "
         "the corresponding profile was active.")
    emit("")

    services = ["gateway", "game-service", "repository", "lobby-service"]
    emit("| Config | Workload | Service | Heap | GC time | GC count | CPU s |")
    emit("|---|---|---|---:|---:|---:|---:|")
    for r in matrix_rows:
        for svc in services:
            heap = heap_used_total(r["final"], svc)
            # Metric naming follows the prometheus-hotspot conventions
            # used by `DefaultJvmMetrics.liveV2`:
            #   jvm_gc_collection_seconds_{sum,count}   ← GC time + pauses
            #   process_cpu_seconds_total               ← CPU consumed
            gct  = delta(r["baseline"], r["final"], svc, "jvm_gc_collection_seconds_sum")
            gcc  = delta(r["baseline"], r["final"], svc, "jvm_gc_collection_seconds_count")
            cpu  = delta(r["baseline"], r["final"], svc, "process_cpu_seconds_total")
            # Don't render rows for services that emitted nothing —
            # tracking would just be noise.
            if heap is None and gct is None and cpu is None:
                continue
            cpu_str = "n/a" if cpu is None else f"{cpu:.2f}"
            emit(
                f"| {r['config']} | {r['workload']} | {svc} | "
                f"{fmt_bytes(heap)} | {fmt_sec(gct)} | "
                f"{fmt_count(gcc)} | {cpu_str} |"
            )
    emit("")

# ────────────── single-run Gatling (when no matrix) ─────────────────────

if not matrix_rows:
    # Look for top-level <backend>/summary.txt — that's perf-run.sh output.
    single_rows = []
    for d in sorted(os.listdir(run_dir)):
        path = os.path.join(run_dir, d)
        if not os.path.isdir(path) or d in ("matrix", "k6", "profiles"):
            continue
        kv = read_kv(os.path.join(path, "summary.txt"))
        if kv:
            single_rows.append({"backend": d, **kv})

    if single_rows:
        emit("## Gatling (single-run cross-backend)")
        emit("")
        emit("| Backend | Mode | Cache | Req OK | Req KO | Mean RPS | p50 ms | p95 ms | p99 ms |")
        emit("|---|---|---|---:|---:|---:|---:|---:|---:|")
        for r in single_rows:
            emit(
                f"| {r.get('backend', '?')} | {r.get('mode', '?')} | "
                f"{r.get('cache', 'none')} | {r.get('requests_ok', '?')} | "
                f"{r.get('requests_ko', '?')} | {r.get('mean_rps', '?')} | "
                f"{r.get('p50_ms', '?')} | {r.get('p95_ms', '?')} | "
                f"{r.get('p99_ms', '?')} |"
            )
        emit("")

# ──────────────────────── k6 surfaces ───────────────────────────────────

k6_dir = os.path.join(run_dir, "k6")
if os.path.isdir(k6_dir):
    emit("## k6 surfaces")
    emit("")
    emit("Layer 1b — surfaces Gatling can't reach. See `k6/README.md` for the "
         "design notes and `docs/perf-experiments.md` for what each surface "
         "tests.")
    emit("")
    for surface in sorted(os.listdir(k6_dir)):
        s_path = os.path.join(k6_dir, surface)
        if not os.path.isdir(s_path):
            continue
        sj = os.path.join(s_path, "summary.json")
        if not os.path.isfile(sj):
            continue
        try:
            d = json.load(open(sj))
        except json.JSONDecodeError:
            continue
        emit(f"### Surface: {surface}")
        emit("")
        metrics = d.get("metrics", {})
        if surface == "browser":
            lcp = metrics.get("browser_web_vital_lcp", {}).get("values", {})
            fcp = metrics.get("browser_web_vital_fcp", {}).get("values", {})
            cls = metrics.get("browser_web_vital_cls", {}).get("values", {})
            iters = metrics.get("iterations", {}).get("values", {}).get("count", "?")
            emit("| Metric | p50 | p95 | p99 | max |")
            emit("|---|---:|---:|---:|---:|")
            emit(f"| LCP (ms) | {lcp.get('med', '?'):.1f} | {lcp.get('p(95)', '?'):.1f} | {lcp.get('p(99)', '?'):.1f} | {lcp.get('max', '?'):.1f} |"
                 if 'med' in lcp else "| LCP (ms) | n/a | n/a | n/a | n/a |")
            emit(f"| FCP (ms) | {fcp.get('med', '?'):.1f} | {fcp.get('p(95)', '?'):.1f} | {fcp.get('p(99)', '?'):.1f} | {fcp.get('max', '?'):.1f} |"
                 if 'med' in fcp else "| FCP (ms) | n/a | n/a | n/a | n/a |")
            emit(f"| CLS      | {cls.get('med', '?'):.3f} | {cls.get('p(95)', '?'):.3f} | {cls.get('p(99)', '?'):.3f} | {cls.get('max', '?'):.3f} |"
                 if 'med' in cls else "| CLS      | n/a | n/a | n/a | n/a |")
            emit(f"")
            emit(f"Iterations completed: **{iters}**.")
        elif surface == "grpc":
            dur = metrics.get("grpc_req_duration", {}).get("values", {})
            iters = metrics.get("iterations", {}).get("values", {}).get("count", "?")
            checks = d.get("root_group", {}).get("checks", [])
            tx_pass = sum(c.get("passes", 0) for c in checks)
            tx_fail = sum(c.get("fails",  0) for c in checks)
            emit("| Metric | p50 | p95 | p99 | max |")
            emit("|---|---:|---:|---:|---:|")
            emit(f"| RPC duration (ms) | {dur.get('med', 0):.1f} | "
                 f"{dur.get('p(95)', 0):.1f} | {dur.get('p(99)', 0):.1f} | "
                 f"{dur.get('max', 0):.1f} |")
            emit("")
            emit(f"Iterations: **{iters}**. Checks: **{tx_pass}** passed, "
                 f"**{tx_fail}** failed.")
        elif surface == "kafka":
            w = metrics.get("kafka_writer_write_seconds", {}).get("values", {})
            err = metrics.get("kafka_writer_error_count", {}).get("values", {}).get("count", 0)
            iters = metrics.get("iterations", {}).get("values", {}).get("count", "?")
            emit("| Metric | p50 | p95 | p99 | max |")
            emit("|---|---:|---:|---:|---:|")
            emit(f"| Produce latency (ms) | {(w.get('med', 0)*1000):.1f} | "
                 f"{(w.get('p(95)', 0)*1000):.1f} | "
                 f"{(w.get('p(99)', 0)*1000):.1f} | "
                 f"{(w.get('max', 0)*1000):.1f} |")
            emit("")
            emit(f"Messages produced: **{iters}**. Producer errors: **{err}**.")
        emit("")

# ──────────────────────── JMH bench ─────────────────────────────────────

bench_files = []  # list of (label, path) — label is the scope inferred from filename
# perf-all moves the aggregate `bench.json` into the run dir
inline = os.path.join(run_dir, "bench.json")
if os.path.isfile(inline):
    bench_files.append(("all", inline))
# Subset / bare bench JSONs land at the perf-reports root as
# bench-<scope>-<ts>.json (scope ∈ codec, rules, persistence, wire) or
# bench-<ts>.json (full suite from bare `make bench`).
parent = os.path.dirname(run_dir.rstrip("/"))
if os.path.isdir(parent):
    for f in sorted(os.listdir(parent)):
        if not (f.startswith("bench-") and f.endswith(".json")):
            continue
        path = os.path.join(parent, f)
        stem = f[len("bench-"):-len(".json")]
        # Filenames: bench-<scope>-<ts>.json OR bench-<ts>.json (no scope,
        # canonical full run from `make bench` or `make perf-all`).
        # Either way, peel off the trailing 16-char timestamp.
        ts_re = re.compile(r"^\d{8}T\d{6}Z$")
        if ts_re.match(stem):
            label = "all"
        else:
            parts = stem.rsplit("-", 1)
            if len(parts) == 2 and ts_re.match(parts[1]):
                label = parts[0] or "all"
            else:
                label = stem
        bench_files.append((label, path))

# Drop duplicates by path while preserving order.
seen = set()
bench_files = [(l, p) for l, p in bench_files if p not in seen and not seen.add(p)]

# Group results by scope label. Within a scope, the most recent file wins
# (later JSONs in `sorted(...)` come from later timestamps).
benches_by_scope = {}
for label, path in bench_files:
    try:
        benches_by_scope[label] = (path, json.load(open(path)))
    except (FileNotFoundError, json.JSONDecodeError):
        continue

if benches_by_scope:
    emit("## JMH microbenchmarks")
    emit("")
    # Render one sub-table per scope so the reader can tell which subset
    # produced which numbers. Scopes are sorted with the special `all`
    # first (canonical full run from `make bench` / `make perf-all`).
    scope_order = ["all", "codec", "rules", "wire", "persistence"]
    ordered = (
        [s for s in scope_order if s in benches_by_scope] +
        [s for s in benches_by_scope if s not in scope_order]
    )
    for scope in ordered:
        path, data = benches_by_scope[scope]
        emit(f"### Scope: `{scope}`")
        emit("")
        emit(f"Source: `{path}`")
        emit("")
        emit("| Benchmark | Mode | Score | Error | Unit |")
        emit("|---|---|---:|---:|---|")
        def _flt(x):
            # JMH writes scoreError as the string "NaN" when there's
            # only one measurement sample (BENCH_QUICK=true) — guard
            # against that and any other non-numeric write.
            try: return float(x)
            except (TypeError, ValueError): return float("nan")
        for b in data:
            name = b.get("benchmark", "?")
            mode = b.get("mode", "?")
            prim = b.get("primaryMetric", {})
            score = _flt(prim.get("score", 0.0))
            err   = _flt(prim.get("scoreError", 0.0))
            unit  = prim.get("scoreUnit", "?")
            short = re.sub(r"^chess\.bench\.", "", name)
            err_str = "n/a" if err != err else f"±{err:,.2f}"  # NaN check
            emit(f"| `{short}` | {mode} | {score:,.2f} | {err_str} | {unit} |")
        emit("")

# ──────────────────────── raw artifacts ─────────────────────────────────

emit("## Raw artifacts")
emit("")
emit(f"Browse the run dir at `{run_dir}/` for the underlying data:")
emit("")
artifacts = []
for root, dirs, files in os.walk(run_dir):
    # Don't recurse into Gatling's deep style/js subtrees in the listing.
    rel = os.path.relpath(root, run_dir)
    depth = 0 if rel == "." else rel.count(os.sep) + 1
    if depth > 3:
        continue
    for name in files:
        if name.endswith(".html") and "gatling" in root.lower():
            continue
        path = os.path.relpath(os.path.join(root, name), run_dir)
        artifacts.append(path)
artifacts.sort()
for a in artifacts[:80]:
    emit(f"- `{a}`")
if len(artifacts) > 80:
    emit(f"- … +{len(artifacts) - 80} more files (Gatling HTML report tree)")
emit("")

# ──────────────────────── write ─────────────────────────────────────────

with open(out_path, "w") as f:
    f.write("\n".join(lines))
print(f"performance-test-results.md → {out_path}")
PY

echo
echo "Done. Open $RUN_DIR/performance-test-results.md."
